spring:
  application:
    name: settlement-engine
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: settlement-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/betting_engine_db}
    username: ${SPRING_DATASOURCE_USERNAME:betting_user}
    password: ${SPRING_DATASOURCE_PASSWORD:betting_password}
    hikari:
      maximum-pool-size: 20

logging:
  level:
    com.betting: INFO
